"""create users table

Revision ID: 49820e0d1225
Revises: 237cba36f03d
Create Date: 2025-07-08 15:38:26.657307

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49820e0d1225'
down_revision = '237cba36f03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jinro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('test_result', sa.JSON(), nullable=True),
    sa.Column('test', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jinro_id'), 'jinro', ['id'], unique=False)
    op.create_index(op.f('ix_jinro_user_id'), 'jinro', ['user_id'], unique=False)
    op.alter_column('embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_jinro_user_id'), table_name='jinro')
    op.drop_index(op.f('ix_jinro_id'), table_name='jinro')
    op.drop_table('jinro')
    # ### end Alembic commands ###
