"""create JR table

Revision ID: 96326ac1eef8
Revises: ca472df78bce
Create Date: 2025-07-10 16:09:55.280085

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '96326ac1eef8'
down_revision = 'ca472df78bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jinroresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jinro_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('stability_score', sa.Integer(), nullable=False),
    sa.Column('creativity_score', sa.Integer(), nullable=False),
    sa.Column('social_service_score', sa.Integer(), nullable=False),
    sa.Column('ability_development_score', sa.Integer(), nullable=False),
    sa.Column('conservatism_score', sa.Integer(), nullable=False),
    sa.Column('social_recognition_score', sa.Integer(), nullable=False),
    sa.Column('autonomy_score', sa.Integer(), nullable=False),
    sa.Column('self_improvement_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jinro_id'], ['jinro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jinroresult_id'), 'jinroresult', ['id'], unique=False)
    op.create_index(op.f('ix_jinroresult_jinro_id'), 'jinroresult', ['jinro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jinroresult_jinro_id'), table_name='jinroresult')
    op.drop_index(op.f('ix_jinroresult_id'), table_name='jinroresult')
    op.drop_table('jinroresult')
    # ### end Alembic commands ###
