"""add_cascade_delete_to_resume_embeddings

Revision ID: e31b31b637d8
Revises: 096bf929e23d
Create Date: 2025-07-06 23:22:21.577592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e31b31b637d8'
down_revision = '096bf929e23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing foreign key constraint
    op.drop_constraint('resume_embeddings_resume_id_fkey', 'resume_embeddings', type_='foreignkey')
    
    # Add new foreign key constraint with CASCADE
    op.create_foreign_key(
        'resume_embeddings_resume_id_fkey',
        'resume_embeddings',
        'resumes',
        ['resume_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CASCADE foreign key constraint
    op.drop_constraint('resume_embeddings_resume_id_fkey', 'resume_embeddings', type_='foreignkey')
    
    # Restore original foreign key constraint without CASCADE
    op.create_foreign_key(
        'resume_embeddings_resume_id_fkey',
        'resume_embeddings',
        'resumes',
        ['resume_id'],
        ['id']
    )
    # ### end Alembic commands ###
