"""create init_table

Revision ID: f19f04113dc6
Revises: d7b47aa941d3
Create Date: 2025-07-17 16:15:03.084527

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f19f04113dc6'
down_revision = 'd7b47aa941d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('similar_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_keywords_id'), 'resume_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_resume_keywords_resume_id'), 'resume_keywords', ['resume_id'], unique=False)
    op.alter_column('jinro_result', 'first_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jinro_result', 'first_job_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('jinro_result', 'second_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jinro_result', 'second_job_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('jinro_result', 'third_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jinro_result', 'third_job_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('resumes', 'analysis_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'analysis_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('jinro_result', 'third_job_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('jinro_result', 'third_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jinro_result', 'second_job_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('jinro_result', 'second_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jinro_result', 'first_job_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('jinro_result', 'first_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_resume_keywords_resume_id'), table_name='resume_keywords')
    op.drop_index(op.f('ix_resume_keywords_id'), table_name='resume_keywords')
    op.drop_table('resume_keywords')
    # ### end Alembic commands ###
